stages:
  - setup
  - test
  - app-test
  - cleanup

aws-cluster:
  image: atulabhi/kops:v8
  stage: setup
  script: 
    - chmod u+x ./script/aws
    - ./script/aws

  artifacts:
    paths:
      - aws/

openebs_aws_deploy:
  image: atulabhi/kops:v8
  stage: test
  dependencies:
    - aws-cluster
  script: 
   - echo "deploying OpenEBS on AWS"
   - ls -a
   - ls -a aws
   - pwd
   - mkdir ~/.kube
   - cp  aws/config ~/.kube/config
   - https://raw.githubusercontent.com/ashishranjan738/testlit/master/openebsinstaller0.6.yaml
   - kubectl apply -f openebsinstaller0.6.yaml

apps-aws-deploy:
  image: atulabhi/kops:v8
  stage: app-test
  script: 
   - echo "jobs-aws-started"
   - wget https://raw.githubusercontent.com/shashank855/litmus/percona_test/apps/percona/deployers/deploy_percona_litmus.yaml
   - kubectl apply -f deploy_percona_litmus.yaml

cleanup-aws:
  when: always
  image: atulabhi/kops:v8
  dependencies:
    - aws-cluster
  stage: cleanup
  script: 
    - chmod u+x ./script/aws-cleanup
    - ./script/aws-cleanup
