stages:
  - cluster-setup
  - infra-setup
  - stateful-apps-deploy
  - chaos-test
  - cleanup
  - deploy

aws-cluster:
  image: atulabhi/kops:v8
  stage: cluster-setup
  script: 
    - chmod 755 ./script/aws
    - ./script/aws

  artifacts:
    paths:
      - aws/

openebs-aws-deploy:
  image: atulabhi/kops:v8
  stage: infra-setup
  dependencies:
    - aws-cluster
  script: 
   - echo "deploying OpenEBS on AWS"
   - chmod 775 ./script/infra-setup
   - ./script/infra-setup
  
  artifacts:
    paths:
      - aws-openebs/

percona-aws-deploy:
  image: atulabhi/kops:v8
  stage: stateful-apps-deploy
  dependencies:
    - openebs-aws-deploy
  script: 
   #- echo "jobs-AWS-Started"
   - chmod 775 ./script/percona-app-deploy
   - ./script/percona-app-deploy

  artifacts:
    paths:
      - aws-openebs/

mongo-aws-deploy:
  image: atulabhi/kops:v8
  stage: stateful-apps-deploy
  dependencies:
    - openebs-aws-deploy
  script: 
   #- echo "jobs-AWS-Started"
   - chmod 775 ./script/mongo-app-deploy
   - ./script/mongo-app-deploy

  artifacts:
    paths:
      - aws-openebs/

postgres-aws-deploy:
  image: atulabhi/kops:v8
  stage: stateful-apps-deploy
  dependencies:
    - openebs-aws-deploy
  script: 
   #- echo "jobs-AWS-Started"
   - chmod 775 ./script/postgres-app-deploy
   - ./script/postgres-app-deploy

  artifacts:
    paths:
      - aws-openebs/


cassandra-aws-deploy:
  image: atulabhi/kops:v8
  stage: stateful-apps-deploy
  dependencies:
    - openebs-aws-deploy
  script: 
   #- echo "jobs-AWS-Started"
   - chmod 775 ./script/cassandra-app-deploy
   - ./script/cassandra-app-deploy

  artifacts:
    paths:
      - aws-openebs/


jenkins-aws-deploy:
  image: atulabhi/kops:v8
  stage: stateful-apps-deploy
  dependencies:
    - openebs-aws-deploy
  script: 
   #- echo "jobs-AWS-Started"
   - chmod 775 ./script/jenkins-app-deploy
   - ./script/jenkins-app-deploy

  artifacts:
    paths:
      - aws-openebs/

Litmus-Chaos:
  image: atulabhi/kops:v8
  dependencies:
    - percona-aws-deploy
  stage: chaos-test
  script:
   - chmod 775 ./script/app-chaos
   - ./script/app-chaos

  artifacts:
    paths:
      - aws-openebs/

cleanup-aws:
  when: always
  image: atulabhi/kops:v8
  dependencies:
    - aws-cluster
  stage: cleanup
  script: 
    - chmod 755 ./script/aws-cleanup
    - ./script/aws-cleanup
